# Generated by Django 5.1.5 on 2025-02-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combinedbackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_password', models.CharField(blank=True, max_length=50, null=True)),
                ('user_group_id', models.IntegerField(blank=True, null=True)),
                ('user_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('user_dob', models.DateTimeField(blank=True, null=True)),
                ('user_resume_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_aadhaar_number', models.BigIntegerField(blank=True, null=True)),
                ('user_pan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('current_otp', models.BigIntegerField(blank=True, null=True)),
                ('is_current_otp_expired', models.IntegerField(blank=True, null=True)),
                ('user_image_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('present_address', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=500, null=True)),
                ('present_village', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('present_city', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('present_district', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('present_state', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('native_address', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=500, null=True)),
                ('native_village', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('native_city', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('native_district', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('native_state', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=100, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.TextField(blank=True, null=True)),
                ('end_year', models.TextField(blank=True, null=True)),
                ('percentage_or_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referral_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_person_email', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_person_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'combinedbackup',
            },
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=100)),
                ('useremail', models.CharField(db_column='UserEmail', max_length=100, unique=True)),
                ('usercontactnumber', models.CharField(db_column='UserContactNumber', max_length=50, unique=True)),
                ('userpassword', models.CharField(db_column='UserPassword', max_length=50, unique=True)),
                ('usergender', models.CharField(db_column='UserGender', max_length=1)),
                ('userdob', models.DateTimeField(db_column='UserDOB', null=True)),
                ('userresumename', models.CharField(db_column='UserResumeName', max_length=100, null=True)),
                ('userresumedata', models.TextField(blank=True, db_column='UserResumeData', null=True)),
                ('useraadhaarnumber', models.BigIntegerField(db_column='UserAadhaarNumber', null=True, unique=True)),
                ('userpannumber', models.CharField(blank=True, db_column='UserPanNumber', max_length=100, null=True, unique=True)),
                ('currentotp', models.BigIntegerField(db_column='CurrentOTP', null=True, unique=True)),
                ('iscurrentotpexpired', models.IntegerField(db_column='IsCurrentOTPExpired', null=True)),
                ('userimagefilename', models.CharField(db_column='UserImageFileName', max_length=50, null=True, unique=True)),
                ('isactive', models.IntegerField(db_column='IsActive', null=True)),
                ('createdby', models.IntegerField(db_column='CreatedBy')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
                ('updateddate', models.DateTimeField(auto_now_add=True, db_column='UpdatedDate', null=True)),
            ],
            options={
                'db_table': 'userdetail',
            },
        ),
        migrations.CreateModel(
            name='Usergroupdetail',
            fields=[
                ('usergroupid', models.AutoField(db_column='UserGroupId', primary_key=True, serialize=False)),
                ('usergroupname', models.CharField(db_column='UserGroupName', max_length=100, unique=True)),
                ('usergroupdescription', models.CharField(blank=True, db_column='UserGroupDescription', max_length=1000, null=True)),
                ('isactive', models.TextField(blank=True, db_column='IsActive', null=True)),
                ('createdby', models.IntegerField(db_column='CreatedBy')),
                ('createddate', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modifiedby', models.IntegerField(blank=True, db_column='ModifiedBy', null=True)),
                ('modifieddate', models.DateTimeField(auto_now_add=True, db_column='ModifiedDate', null=True)),
            ],
            options={
                'db_table': 'usergroupdetail',
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('referralid', models.AutoField(db_column='ReferralId', primary_key=True, serialize=False)),
                ('referralpersonname', models.CharField(db_column='ReferralPersonName', max_length=100, null=True)),
                ('referralpersonemail', models.CharField(db_column='ReferralPersonEmail', max_length=100, null=True, unique=True)),
                ('referralpersonphone', models.CharField(db_column='ReferralPersonPhone', max_length=15, null=True)),
                ('referraldate', models.DateTimeField(blank=True, db_column='ReferralDate', null=True)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userdetail')),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='Professionaldetail',
            fields=[
                ('professionalid', models.AutoField(db_column='ProfessionalId', primary_key=True, serialize=False)),
                ('jobtitle', models.CharField(db_column='JobTitle', max_length=100, null=True)),
                ('companyname', models.CharField(db_column='CompanyName', max_length=200, null=True)),
                ('startdate', models.DateField(db_column='StartDate', null=True)),
                ('enddate', models.DateField(db_column='EndDate', null=True)),
                ('currentctc', models.DecimalField(db_column='CurrentCTC', decimal_places=2, max_digits=10, null=True)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userdetail')),
            ],
            options={
                'db_table': 'professionaldetail',
            },
        ),
        migrations.CreateModel(
            name='Educationdetail',
            fields=[
                ('educationid', models.AutoField(db_column='EducationId', primary_key=True, serialize=False)),
                ('degreename', models.CharField(db_column='DegreeName', max_length=100, null=True)),
                ('institutionname', models.CharField(db_column='InstitutionName', max_length=200, null=True)),
                ('universityname', models.CharField(db_column='UniversityName', max_length=200, null=True)),
                ('startyear', models.TextField(db_column='StartYear', null=True)),
                ('endyear', models.TextField(db_column='EndYear', null=True)),
                ('percentageorcgpa', models.DecimalField(db_column='PercentageOrCGPA', decimal_places=2, max_digits=5, null=True)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userdetail')),
            ],
            options={
                'db_table': 'educationdetail',
            },
        ),
        migrations.CreateModel(
            name='Addressdetail',
            fields=[
                ('addressid', models.AutoField(db_column='AddressId', primary_key=True, serialize=False)),
                ('presentaddress', models.CharField(db_collation='utf8mb3_general_ci', db_column='PresentAddress', max_length=500, null=True, unique=True)),
                ('presentvillage', models.CharField(db_collation='utf8mb3_general_ci', db_column='PresentVillage', max_length=100, null=True)),
                ('presentcity', models.CharField(db_collation='utf8mb3_general_ci', db_column='PresentCity', max_length=100, null=True)),
                ('presentdistrict', models.CharField(db_collation='utf8mb3_general_ci', db_column='PresentDistrict', max_length=100, null=True)),
                ('presentstate', models.CharField(db_collation='utf8mb3_general_ci', db_column='PresentState', max_length=100, null=True)),
                ('nativeaddress', models.CharField(db_collation='utf8mb3_general_ci', db_column='NativeAddress', max_length=500, null=True, unique=True)),
                ('nativevillage', models.CharField(db_collation='utf8mb3_general_ci', db_column='NativeVillage', max_length=100, null=True)),
                ('nativecity', models.CharField(db_collation='utf8mb3_general_ci', db_column='NativeCity', max_length=100, null=True)),
                ('nativedistrict', models.CharField(db_collation='utf8mb3_general_ci', db_column='NativeDistrict', max_length=100, null=True)),
                ('nativestate', models.CharField(db_collation='utf8mb3_general_ci', db_column='NativeState', max_length=100, null=True)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userdetail')),
            ],
            options={
                'db_table': 'addressdetail',
            },
        ),
        migrations.AddField(
            model_name='userdetail',
            name='usergroupid',
            field=models.ForeignKey(db_column='UserGroupId', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usergroupdetail'),
        ),
    ]
