# Generated by Django 5.1.5 on 2025-02-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='useraadhaarnumber',
            field=models.BigIntegerField(blank=True, db_column='UserAadhaarNumber', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userdob',
            field=models.DateTimeField(blank=True, db_column='UserDOB', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userimagefilename',
            field=models.CharField(blank=True, db_column='UserImageFileName', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userresumename',
            field=models.CharField(blank=True, db_column='UserResumeName', max_length=100, null=True),
        ),
    ]
