# Generated by Django 5.1.5 on 2025-02-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userdetail_useraadhaarnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedbackup',
            name='user_id',
            field=models.ForeignKey(db_column='UserId', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='userid',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail'),
        ),
        migrations.AlterField(
            model_name='professionaldetail',
            name='userid',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail'),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='userid',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='accounts.userdetail'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='usergroupid',
            field=models.ForeignKey(db_column='UserGroupId', on_delete=django.db.models.deletion.CASCADE, to='accounts.usergroupdetail'),
        ),
    ]
